name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job-1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: echho
        shell: bash
        run: echo ${{github.workspace}}
  job-2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: echho
        shell: bash
        run: echo ${{github.workspace}}       
  job-3:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v1
     - name: echho
       shell: bash
       run: echo ${{github.workspace}}

