name: C/C++ CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job-1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: something
        shell: bash
        run: echo `pwd`/hiha/`pwd`
      
